title: Libertarian Constitutional Reform
description: A collaborative project to reform governance for liberty.
baseurl: "/nueva-constitucion"  # Matches your repo name
url: "https://dubdam.github.io"  # Your GitHub Pages domain
theme: minima
